### ISSUE TITLE
Icon suggestions

### ISSUE THREAD

**Issue by alexdesiqueira** [SethStormR/Shade-of-Z#1]
Thank you for these icons @SethStormR, they look great!
Some app suggestions:
* VSCode
* Emacs
* Liferea
* Xournal
* Zotero
* Slack
* pCloud
* Discord
These are the ones I have in my bar right now :joy: 
Thanks again!

**Comment by SethStormR** [comment]
Hi,

I'll look into it.

Discord should be there. Can you check the icon name of Discord? Usually /usr/share/applications but if it's a snap/flatpack it may have hardcoded icon. Then you have to set it manually.

![discord](https://user-images.githubusercontent.com/60283532/118853631-3d8a8d80-b8d4-11eb-8bf1-f978a0a219c6.png)

VSCode - Open source or Microsofts?

**Comment by alexdesiqueira** [comment]
Thank you for your prompt answer, @SethStormR!
* On Discord: I installed mine using their deb package.
```
❯ which discord
/usr/bin/discord
```
* On VSCode: VSCode is Microsoft, the OS version is called [VSCodium](https://vscodium.com/). Their icon is different: https://github.com/VSCodium/. (edit) I personally use Microsoft's.
Thanks again!

**Comment by SethStormR** [comment]
That's puzzling. I installed the .deb file of discord to track its icon. The name of the of the image file is just **discord**. So I thought it might be a bug on my side in one of my icon sets, but all my icon sets have discord.(svg).
Can you open the file  /usr/share/applications/discord.desktop with an editor and tell me what it says under **icon=**, thanks.

**Comment by alexdesiqueira** [comment]
Sure! The file follows:
```
[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/share/discord/Discord
Icon=discord
Type=Application
Categories=Network;InstantMessaging;
Path=/usr/bin
```
Thank you!

**Comment by SethStormR** [comment]
Which color do you use of "Shade of Z"?

As you can see mine changed, so I'm bit baffled your aren't:

![menu](https://user-images.githubusercontent.com/60283532/118886872-d54ea280-b8f9-11eb-982c-2c5d2402d07e.png)

**Comment by alexdesiqueira** [comment]
Never mind! Reinstalled it, it seems okay now:
![image](https://user-images.githubusercontent.com/5776022/118887354-19688580-b8af-11eb-8366-f7df429ef0b9.png)
Thank you!

**Comment by SethStormR** [comment]
Hi,

Try and see if all the icons for your listed apps are changed. I also fixed the zoom icon.
[Shade of Z - Black-v.0.4alpha.zip](https://github.com/SethStormR/Shade-of-Z/files/6511980/Shade.of.Z.-.Black-v.0.4alpha.zip)

**Comment by alexdesiqueira** [comment]
Thank you @SethStormR! These look great!
![image](https://user-images.githubusercontent.com/5776022/118898466-710fec80-b8c1-11eb-9867-3329536c0399.png)
For the ones it didn't find,
```
❯ which emacs
/usr/bin/emacs
❯ which zotero
/usr/local/bin/zotero
```
Again, that's more than nice. Appreciate it, owe ya a beer!

**Comment by SethStormR** [comment]
It's an ever hunting for icon names. It would be easier if they all use the same icon name disregard of who packaged them. I'll se what I can do.

**Comment by SethStormR** [comment]
The Zotero. It comes in various packages. Which package/installation did you use. Their homepage have the default tarball, a look into it I could see it was hardcoded, in that case you have to manually change the icon. They are also referring to a .deb package?

**Comment by SethStormR** [comment]
It's getting late here, but try this one. If you used the .deb package of Slack it's also hardcoded and need manually change with the menu editor.

This should fix emacs, if not let me know what /usr/share/applications/<emacs>.desktop looks like.
[Shade of Z - Black-v0.4alpha2.zip](https://github.com/SethStormR/Shade-of-Z/files/6512114/Shade.of.Z.-.Black-v0.4alpha2.zip)

**Comment by alexdesiqueira** [comment]
On Zotero:
> The Zotero. It comes in various packages. Which package/installation did you use. Their homepage have the default tarball, a look into it I could see it was hardcoded, in that case you have to manually change the icon. They are also referring to a .deb package?

I'm using this one: https://github.com/retorquere/zotero-deb
On `/usr/share/applications/zotero.desktop`:
```
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager
Exec=/usr/lib/zotero/zotero --url %u
Icon=/usr/lib/zotero/chrome/icons/default/default256.png
Type=Application
Categories=Office;Education;Literature
StartupNotify=true
MimeType=x-scheme-handler/zotero;application/x-endnote-refer;application/x-research-info-systems;text/ris;text/x-research-info-systems;application/x-inst-for-Scientific-info;application/mods+xml;application/rdf+xml;application/x-bibtex;text/x-bibtex;application/marc;application/vnd.citationstyles.style+xml
```

**Comment by alexdesiqueira** [comment]
On Emacs:
> This should fix emacs, if not let me know what /usr/share/applications/.desktop looks like.

Emacs should be a _very_ different beast. Their names are different according to the version! :joy: 
On `/usr/share/applications/emacs27.desktop`:

```
[Desktop Entry]
Name=Emacs
GenericName=Text Editor
Comment=Edit text
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
Exec=emacs27 %F
Icon=emacs27
Type=Application
Terminal=false
Categories=Development;TextEditor;
StartupWMClass=Emacs
Keywords=Text;Editor;
```

I think the version available on the repos is Emacs 2.6, though.
Again, thank you for that man. Don't worry; you did a lot already :slightly_smiling_face:

**Comment by SethStormR** [comment]
I'll put emacs26.svg and emacs27.svg in the next update. The github will have v.0.4 on sunday and pling on wedensday (due to their anti-spam policy).
I'll close this requests. If you have other requests please open a new issue. :)

**Comment by alexdesiqueira** [comment]
Thank you @SethStormR! Appreciate all your effort on this package, and thanks for your time on answering me.
Owe ya a beer! :beers:
