### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by maydayv7** [SethStormR/Shade-of-Z#2]
Please make icons for the following apps:

- [x] BlueJ
- [x] Apostrophe
- [x] Fragments
- [x] Shotwell
- [x] Foliate
- [x] Drawing
- [x] Bottles
- [x] Giara
- [x] OnlyOffice
- [x] Flameshot
- [x] Gscan2pdf
- [x] Calibre
- [x] Gnome Password Safe
- [x] Gnome Games
- [x] Gnome Dictionary and Books
- [x] gFeeds
- [x] Gnome Chess and 2048
- [x] Gnome Music
- [x] Epiphany or Gnome Web
- [x] Gnome Usage

**Comment by SethStormR** [comment]
Hi,

I'll se what I can do, they can't make it to the next release (2.0b). But I'll aim for they can get in v2.0c.
If you use snap, make sure to set the icon(s) manually with a menu editor application.
I can see that in  my icon index that I have made icon for OnlyOffice - which method did you use to install it (.deb/flat/snap/other)?

**Comment by maydayv7** [comment]
I have used `git` to clone the repo and then extracted the icons to `~/.icons` in the home folder.  
Also, no pressure, take your time, I love these icons!

**Comment by SethStormR** [comment]
Just found out I was missing a version of OnlyOffice :P 
I new look for OnlyOffice will be in the next release.

![White](https://user-images.githubusercontent.com/60283532/127624354-6ecc4033-36e3-4008-85f4-239e810ddee0.png)

**Comment by maydayv7** [comment]
Thanks!
